import type { Metadata } from "next";
import { Gamja_Flower } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const gamja_Flower = Gamja_Flower({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={gamja_Flower.className}>{children}</body>
    </html>
  );
}
